Handle Case where package does not yet exist
Polymathian/aws-codeartifact-next-version-action pull request #4
Opened 2024-04-02 05:17 UTC by Josh-Zhou

If the package that is being pushed does not yet exist, handle this case by returning null.

@gricey432 will need to verify this behaviour is desirable before merging.

failed action example:
https://github.com/Polymathian/mine_planning_engine/actions/runs/8517015591/job/23327787369

2024-04-02 05:17 UTC, Josh-Zhou commented on versioner.js
> +                return null
this is the main change

2024-04-02 23:47 UTC, liverpool1026 approved these changes
I'm guessing that we never released a new engine after moving from Jenkins, so there will always be a package exist in CodeArtifact

2024-04-07 23:31 UTC, gricey432 requested changes

2024-04-07 23:31 UTC, gricey432 commented on versioner.js
> +            // Temporary solution to catch if the package does not yet exist on code artifact.
Remove comment

2024-04-07 23:31 UTC, gricey432 commented on versioner.js
> +            if (e.code === "ResourceNotFoundException") {
Comment inside this block when you'd expect this to happen

2024-04-08 01:02 UTC, gricey432 approved these changes

2024-04-08 01:03 UTC, merged